TatliSozlukProject/Controllers/AdminCategoryController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using Entities.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TatliSozlukProject.Controllers
{
    public class AdminCategoryController : Controller
    {
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        // GET: AdminCategory

        [Authorize(Roles = "B")] // sadece B rolündeki kişiler bu sayfayı görsün.
        public ActionResult Index()
        {
            var categoryList = cm.GetCatList();
            return View(categoryList);
        }

        [HttpGet]
        public ActionResult CategoryAdd()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CategoryAdd(Category cat)
        {
            CategoryValidator categoryValidator = new CategoryValidator();
            ValidationResult results = categoryValidator.Validate(cat);

            if(results.IsValid)
            {
                cm.AddCategory(cat);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
                
            }
            return View();
        }

        public ActionResult DeleteCategory(int id)
        {
            var categoryValue = cm.GetById(id);
            cm.CategoryDelete(categoryValue);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditCategory(int id)
        {

            // Güncellenecek olan kategoriyi bul.
            var catValue = cm.GetById(id); // id'ye göre gelen valueları değişkene atadık.
            return View(catValue);


        }

        [HttpPost]
        public ActionResult EditCategory(Category cat)
        {
            cm.CategoryUpdate(cat);
            return RedirectToAction("Index");


        }

    }
}

TatliSozlukProject/Views/AdminCategory/CategoryAdd.cshtml
@model Entities.Concrete.Category

@{
    ViewBag.Title = "CategoryAdd";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<h1>Yeni Kategori Ekleme</h1>
<br />

@using (Html.BeginForm("CategoryAdd", "AdminCategory", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kategori Adı:")
        @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryName)
        <br />
        <br />
        @Html.Label("Açıklama giriniz:")
        @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryDescription)
        <br />
        <br />
        <button class="btn btn-info">Kategoriyi Kaydet</button>
    </div>
}

TatliSozlukProject/Views/AdminCategory/EditCategory.cshtml
@model Entities.Concrete.Category

@{
    ViewBag.Title = "EditCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Kategori Güncelle</h2>
<br />
@using(Html.BeginForm("EditCategory","AdminCategory",FormMethod.Post))
 {
<div class="form-group">
    @Html.Label("Kategori ID")
    @Html.TextBoxFor(x => x.CategoryID, new { @class = "form-control" })
    <br />
    @Html.Label("Kategori Adı")
    @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
    <br />
    @Html.Label("Kategori Açıklaması")
    @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Güncelle</button>
</div>
 }

TatliSozlukProject/Views/AdminCategory/Index.cshtml
@using Entities.Concrete
@model List<Category>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<table class="table table-bordered" style="margin-top:20px;">
    <tr>
        <th>#</th>
        <th>Kategori Adı</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Başlıklar</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <th>@item.CategoryID</th>
            <td>@item.CategoryName</td>
            <td><a href="/AdminCategory/DeleteCategory/@item.CategoryID" class="btn btn-danger">Sil</a></td>
            <td><a href="/AdminCategory/EditCategory/@item.CategoryID" class="btn btn-warning">Güncelle</a></td>
            <td><a href="#" class="btn btn-primary">Başlıklar</a></td>

        </tr>

    }
</table>
<a href="/AdminCategory/CategoryAdd" class="btn btn-info">Yeni Kategori Ekle</a>