TatliSozlukProject/Controllers/AuthorPanelContentController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TatliSozlukProject.Controllers
{
    public class AuthorPanelContentController : Controller
    {
        ContentManager contentManager = new ContentManager(new EfContentDal());
        Context c = new Context();
        public ActionResult MyContent(string p)
        {
           
            p = (string)Session["AuthorMail"];
            // sisteme giriş yapılan mailin id'sini al.
            var authorIDInfo = c.Authors.Where(x => x.AuthorMail == p).Select(y => y.AuthorID).FirstOrDefault();
            var contentValues = contentManager.GetContentByAuthor(authorIDInfo);
            return View(contentValues);
        }
        [HttpGet]
        public ActionResult AddContent(int id)
        {
            ViewBag.d = id;
            return View();
        }

        [HttpPost]
        public ActionResult AddContent(Content content)
        {
            string mail = (string)Session["AuthorMail"];
            // sisteme giriş yapılan mailin id'sini al.
            var authorIDInfo = c.Authors.Where(x => x.AuthorMail == mail).Select(y => y.AuthorID).FirstOrDefault();
            content.ContentDate = DateTime.Parse(DateTime.Now.ToShortTimeString());
            content.AuthorID = authorIDInfo;
            content.ContentStatus = true;
            contentManager.AddContent(content);
            return RedirectToAction("MyContent");
        }

        public ActionResult ToDoList()
        {
            return View();
        }
    }
}

TatliSozlukProject/Views/AuthorPanelContent/AddContent.cshtml
@model Entities.Concrete.Content

@{
    ViewBag.Title = "AddContent";
    Layout = "~/Views/Shared/_AuthorLayout.cshtml";
}

<h2>Başlığa İçerik Ekle</h2>

<br />
@using (Html.BeginForm("AddContent", "AuthorPanelContent", FormMethod.Post))
{
    <div class="form-group">
        <input type="hidden" name="HeadingID" value="@ViewBag.d"/>
        @Html.Label("İçeriğinizi Yazın")
        @Html.TextAreaFor(x => x.ContentText, 10, 30, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.ContentText)
        <br />
        <button class="btn btn-info">İçerik Oluştur</button>
 
    
    </div>
}

TatliSozlukProject/Views/AuthorPanelContent/MyContent.cshtml
@using Entities.Concrete
@model List<Content>
@{
    ViewBag.Title = "MyContent";
    Layout = "~/Views/Shared/_AuthorLayout.cshtml";
}


<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">

                <!-- Timelime example  -->
                <div class="row">
                    <div class="col-md-12">
                        <!-- The time line -->
                        <div class="timeline">
                            <!-- timeline time label -->
                            @foreach (var item in Model)
                            {
                                <div class="time-label">
                                    <span class="bg-success">@(((DateTime)item.ContentDate).ToString("dd MMMM yyyy"))</span>
                                </div>
                                <!-- /.timeline-label -->
                                <!-- timeline item -->
                                <div>
                                    <i class="fas fa-comment bg-yellow"></i>
                                    <div class="timeline-item">
                                        <h3 class="timeline-header"><a href="#">@item.Heading.HeadingName</a></h3>
                                        <div class="timeline-body">
                                            @item.ContentText
                                        </div>
                                    </div>
                                </div>
                            }
                            <!-- END timeline item -->
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->
</body>
</html>

TatliSozlukProject/Views/AuthorPanelContent/ToDoList.cshtml
@{
    ViewBag.Title = "ToDoList";
    Layout = "~/Views/Shared/_AuthorLayout.cshtml";
}

<p>#1 Profilim</p>
<p>#2 Tüm başlıklarda paging</p>
<p>#3 Mesajlarda session </p>
<p>#4 Oturum yönetiminin mimariye taşınması </p>
<p>#5 Token Kullanımı </p>